# Generated by Django 3.1.2 on 2021-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_weight',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
